global.topics = {};

global.topics[$ "Big Boss Room"] = [
	TEXT("With that, the fox followed closely behind the receptionist as she led the way through the grand entrance of the Sunflower Inc. headquarters. The building's interior was just as impressive as its exterior."),
	TEXT("The sleek, eco-friendly design featured a combination of glass walls and lush greenery, giving it a modern yet inviting ambiance."),
	TEXT("As they strolled through the expansive lobby, Jaden couldn't help but marvel at the towering walls adorned with large, framed photographs showcasing the company's solar farms at sunrise and sunset."),
	TEXT("The receptionist led Jaden through a series of pristine corridors, each one seemingly more opulent than the last. Expensive artwork adorned the walls, and the scent of freshly cut flowers filled the air."),
	TEXT("The sound of water gently trickling from a decorative fountain made sure their stroll wasn't completely silent."),

	TEXT("Finally, after what felt like a winding labyrinth, they arrived at a massive, ornate door, unlike any other Jaden had seen."),
	TEXT("The recepcionist knocked on it twice before opening the door and gesturing for the fox to walk in"),

	TEXT("As Jaden entered the lavishly adorned room, he was immediately struck by a sense of opulence that nearly took his breath away."),
	TEXT("It appeared the owner of the most successful energy company in Lumina had spared no expense in creating a haven of extravagance."),
	TEXT("The walls were adorned with rare, shimmering gemstones that cast a soft, ethereal glow throughout the room."),
	TEXT("The floor was a mosaic of imported marble, each tile perfectly aligned to create a seamless sea of opaline patterns."),
	TEXT("However, before the arctic fox could continue his inspection, a tall silhouette approached him and stood right in front of his eyes, blocking vision"),
	
	SPEAKER("Sunflower Employee", spr_employee_spk, PORTRAIT_SIDE.LEFT),
	TEXT("Sir... Mr. Anderson has arrived..."),
	SPEAKER("?", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
	TEXT("Oh, but of course!"),
	TEXT("Ah, Mr. Anderson! Welcome to Sunflower INC, the future of sustainable energy. It's a pleasure to have you on board."),
	SPEAKER("?", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
	TEXT("My name is Charles Sterling, but most people around here call me The Boss, hahahaha!"),
	
	SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
	TEXT("Yeah, yeah, great to be here. Can we skip the welcome party and get to work?"),
	SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
	TEXT("Of course, my boy. But first, let me explain our solar panels. You see, they harness the power of the sun, converting photons into clean electricity."),
	TEXT("It's the cornerstone of our sustainable future!"),
	SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
	TEXT("Fascinating. Now, about my assignment..."),
	SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
	TEXT("And these panels are made from the finest, eco-friendly materials, contributing to Lumina's vibrant ecosystem."),
	SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
	TEXT("I get it, sunlight turns into power, magic happens. What's my mission, again?"),
	SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
	TEXT("Ah, yes! Your mission, my dear Jaden, is to ensure the continuous operation of these solar panels and maintain Lumina's energy supply."),
	SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
	TEXT("Oh, wow, what an honor. Changing light bulbs must be real thrilling work."),
	SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
	TEXT("Oh, Mr. Anderson, I'm afraid your assignment won't be as simple as changing a light bulb.. The company will require you to go out on the field and protect our valuable solar panels"),
	TEXT("from those pesky creatures that insist on appearing once the sun sets..."),
	SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
	TEXT("..."),
	TEXT("Creatures... What kind of creatures?"),
	SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
	TEXT("I'm sure you'll get acquainted with them in the following hours, but our theory is that these monsters are experiments created by an eco-terrorist group to sabotage"),
	TEXT("our solar panels and crush the bright future we are trying to build."),
	
	SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
	TEXT("Yeah, yeah, whateve... As long as I get paid by the end of it..."),
	SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
	TEXT("But what happened to the previous employees? Why'd they quit?"),
	
	SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
	TEXT("Oh, Mr. Anderson... They suffered a simple work accident and are now recovering. Nothing to worry about."),
	
	
	SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
	TEXT("Simple work accident, huh?"),
	
	
	SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
	TEXT("Safety is our top priority here at Sunflower INC, Mr. Anderson. But enough about that. Let's get you your safety clothing and equipment for the mission!"),
];


global.topics[$ "Weapon Room"] = [
TEXT("Mr. Sterling reached into a drawer and produced two items, placing them on the desk. One was a sleek, sun-powered blaster, and the other a finely crafted sword."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Here we have your blaster for ranged combat, and a trusty sword for close encounters. You can switch between them using the 'C' key."),
TEXT("You'll use your mouse to aim, and the left mouse button to shoot. Easy, right?"),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("..."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
TEXT("But that's not all. With how nimble you look, you also must have the ability to roll by pressing the 'Shift' key. This will help you dodge incoming attacks and navigate tight spots."),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("I'll keep that in mind."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
TEXT("Last but not least, you have three stimulants at your disposal for healing. In the heat of battle, press the 'V' key to use one and patch yourself up!"),
TEXT("Remember, Jaden, here at Sunflower Inc., we not only protect our assets but also protect the environment. With your help, we'll ensure that Lumina remains a beacon of green energy!"),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("Suuuuure..."),

SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("But yeah... You mentioned monsters early... What even are those things?"),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("As I told you earlier, our intelligence suggests that they were not a product of nature but rather the creation of ecoterrorists with malicious intent"),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("Ecoterrorists? What do they want?"),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("It appears their goal is to disrupt our green energy initiatives and sow chaos throughout Lumina. These organisms were engineered to feed on the components"),
TEXT("that make up our solar panels and electronic systems. They are designed to disrupt our power supply and plunge the city into darkness."),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("So, they're targeting the source of all energy? Clever..."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Exactly. These creatures pose a significant threat to our way of life here in Lumina. That's why your role as a guard is so crucial. We can't allow them to undermine our commitment to green energy and the well-being of our city."),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("..."),
TEXT("I understand..."),
TEXT("I will stop them, Mr. Sterling..."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
TEXT("I knew we could count on you, Jaden. With your skills and determination, I'm confident that together, we can overcome this threat and preserve the future of Lumina."),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("Yeah yeah... Whatever..."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Now, if you are ready, Ms. Campbell will accompany you to the field."),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("Got it..."),

];

global.topics[$ "Intro"] = [
TEXT("The sun hung low in the sky, casting a warm golden hue over the picturesque town of Lumina. It was a place where the streets glistened with cleanliness,"),
TEXT("and the air felt fresher than anywhere else. Lumina was known far and wide as a shining example of environmental responsibility, where green energy solutions"),
TEXT("were not just a choice, but a way of life. The local news tablets never tired of reporting that Lumina was a place where all energy was green, and it didn't harm the environment."),
TEXT("At least, that's what they said."),

TEXT("In the heart of Lumina, amid the pristine streets and eco-friendly buildings, there was a lone figure making their way through the city. Jaden Anderson, an anthropomorphic Arctic fox, navigated the bustling streets with a cool and composed demeanor."),
TEXT("His striking white fur and piercing blue eyes often turned heads, but he had no time to bask in that attention. Desperation gnawed at him... He felt restless, exhausted... He desperately needed cash, and A LOT of it..."),
TEXT("His little afternoon walk took him past bustling cafes, where patrons of different anthropomorfic species sipped artisanal coffees brewed with what everyone called energy-efficient machines. He strolled beneath solar-powered street lamps."),
TEXT("Even the cars on the road were almost completely quiet with the hum of electric motors..."),

TEXT("As the arctic fox continued through the town, he couldn't help but notice a newspaper stand tucked between a gelato parlor and a bicycle shop. He approached the stand and glanced at the headlines, his keen eyes quickly scanning for opportunities."),
TEXT("There, in HUGE bold letters, he saw it: 'Sunflower Inc. Now Hiring Night Shift Security Guards!'"),

TEXT("Jaden quickly raised an eyebrow... Sunflower Inc. was the biggest and most renowned solar energy company in Lumina, known for its sprawling solar farms that powered the town's energy grid. It was the cornerstone of Lumina's"),
TEXT("green energy reputation. And they were hiring guards for the night shift??"),
TEXT("There was something awfully fishy about this..."),
TEXT("But for now, his gaze lingered on the newspaper. Perhaps this was the opportunity he'd been waiting for."),

TEXT("Jaden folded the newspaper and tucked it under his arm. He made his way through the town's winding streets, following the directions to the Sunflower Inc. facility. As he approached the gates of the company, he sighed cautiously, wondering what kind of job this would be."),
TEXT("Upon arriving, the few guards at the gate allow him in, and one even went as far as to accompany the foxthe fox to the entrance, where he quickly scanned his surroundings and realized he was in some kind of fine reception."),
TEXT("Behind the counter, a dark-haired feline stared at him fixedly. As there didn't seem to be another living soul in that lobby that didn't appear to work there, the fox took a step forward and approached the cat."),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("Hey uh... I'm here for the job offer..."),
SPEAKER("Sunflower Employee", spr_employee_spk, PORTRAIT_SIDE.RIGHT),
TEXT("..."),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("You know... The one in the newspaper ad?"),
SPEAKER("Sunflower Employee", spr_employee_spk, PORTRAIT_SIDE.RIGHT),
TEXT("..."),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("..."),
SPEAKER("Sunflower Employee", spr_employee_spk, PORTRAIT_SIDE.RIGHT),
TEXT("Very well... You look qualified enough... What's your name?"),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("Jaden... Jaden Anderson..."),
SPEAKER("Sunflower Employee", spr_employee_spk, PORTRAIT_SIDE.RIGHT),
TEXT("J-A-D-E-N A-N-D-E-R-S-O-N..."),
TEXT("Give me just a moment to inform the boss that you've ar-"),
TEXT("Done. He's expecting you at his office. Now if you may please follow me."),


];

global.topics[$ "Alive"] = [
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Oh! Thank goodness you picked up! Glad to see my favorite fox is still alive and kicking"),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("Yeah yeah... Whatever... What even were those things!?"),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Bioengineered creatures that want to destroy our solar panels... I thought we had gone through this already..."),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("I mean... Yeah... It was a rhetorical question"),
SPEAKER("Mr. Sterling", spr_bigboss_spk_happy, PORTRAIT_SIDE.RIGHT),
TEXT("In any case, proceed to the next area... Our readings are detecting more of those creatures."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Before that... Though... May I ask you a question?"),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("Sure... I guess..?"),
SPEAKER("Mr. Sterling", spr_bigboss_spk_norm, PORTRAIT_SIDE.RIGHT),
TEXT("Why did you decide to accept this job?"),
TEXT("Of course everyone needs money but... I have a feeling there's more to that..."),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("I-"),
TEXT("..."),
SPEAKER("Jaden", spr_jaden_spk_norm, PORTRAIT_SIDE.LEFT),
TEXT("I need money to help someone I know... She's in the hospital and..."),
SPEAKER("Mr. Sterling", spr_bigboss_spk_sad, PORTRAIT_SIDE.RIGHT),
TEXT("I am... Sorry to hear that... Jaden..."),
SPEAKER("Jaden", spr_jaden_spk_ang, PORTRAIT_SIDE.LEFT),
TEXT("Whatever... Let's get this over with..."),

];
